# model_checkpoint: "checkpoints/multi_modal_model_3/seed_42/best_model.pt"
# model_config: "Configs/model_config.yaml"
# model_version: "TCN_multi_modal_model_2"
data:
  lob_path: "/root/autodl-tmp/test_data/lob_data.npy"
  trade_path: "/root/autodl-tmp/test_data/trade_data.npy"
  label_path: "/root/autodl-tmp/test_data/trade_labels_ret.npy"
  time_bucket_path: "/root/autodl-tmp/test_data/time_bucket.npy"

signal_config:
  history_T: 6000
  signal_stride: 1800
  batch_size: 128
  num_workers: 0
  pin_memory: False
  alpha: 0.0004
  use_amp: true

backtest:
  strategy: "discrete"
  fee_rate: 0.0000
  slippage: 0.0000
  initial_capital: 1000000
  execution_delay: 1
  risk_free_rate: 0.0

output:
  result_dir: "checkpoints/TCN_multi_modal_model_1/Backtest/result"
  log_dir: "checkpoints/TCN_multi_modal_model_1/Backtest/log"
